blank_issues_enabled: false

contact_links:
    - name: â“ Question (Discussions)
      url: https://github.com/mienaiyami/yomikiru/discussions/categories/q-a
      about: "Ask a question about this app"
